name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: conda-forge/setup-conda@v1
      with:
        python-version: 3.8
        channels: conda-forge
        dependencies:
          - g++
          - make

    - name: Build
      run: |
        g++ -o main main.cpp
        ./main
